name: Deploy

on:
  push:
    branches:
      - 'main'

  workflow_dispatch:

jobs:
  check_code:
    name: Build Svordle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.19.1
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Svelte Check
        run: pnpm check
      - name: Lint App
        run: pnpm format
      - name: Build app
        run: pnpm build
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          # this should match the `pages` option in your adapter-static options
          path: 'build/'
  
  deploy:
    needs: check_code
    name: Deploy App
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}		
    
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
