name: Deploy

on:
  push:
    branches:
      - 'main'

  workflow_dispatch:

jobs:
  check-code:
    name: Build Svordle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Svelte Check
        run: npm run check
      - name: Lint App
        run: npm run format
      - name: Build app
        run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          # this should match the `pages` option in your adapter-static options
          path: 'build/'
  
  deploy:
    name: Deploy App
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}		
    
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
