name: PR Checks

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

  workflow_dispatch:

jobs:
  check-code:
    name: Test App Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.19.1
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Svelte Check
        run: pnpm check
      - name: Lint App
        run: pnpm format
      - name: Build app
        run: pnpm build
