name: PR Checks

on:
	pull_request:
		branches:
			- main
		types: 
			- opened
			- synchronize
			- reopened
			- ready_for_review

	workflow_dispatch:

jobs:
	check-code:
		name: Test App Build
		runs-on: ubuntu-latest
		steps:
			- name: Checkout
				uses: actions/checkout@v4
			- name: Install Node.js
				uses: actions/setup-node@v3
				with:
					node-version: 16
					cache: npm
			- name: Install dependencies
				run: npm install
			- name: Svelte Check
				run: npm run check
			- name: Lint App
				run: npm run format
			- name: Build app
				run: npm run build
